### PR TITLE
Move MissingServiceRuntimeException to a top level class

### LINKED ISSUE #28: Make MissingServiceRuntimeException public
Consider moving to a top-level class.

Also consider moving the static factory method `newMissingServiceRuntimeException` into the exception. Might want to rename it, e.g.

```java
throw new MissingServiceRuntimeException.from(serviceIdentifier);
```

### PR DESCRIPTION
**Pull request by chrisrohr**
Fixes #28

### CODE REVIEW

**Comment by chrisrohr** [comment]
Do you want a dedicated test for the Exception class?  It is fully covered by the existing tests.

File: src/main/java/org/kiwiproject/jersey/client/exception/MissingServiceRuntimeException.java [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+import org.kiwiproject.jersey.client.ServiceIdentifier;
+
+import java.util.Optional;
+
+public class MissingServiceRuntimeException extends RuntimeException {
+    public MissingServiceRuntimeException(String message) {
+        super(message);
+    }
+
+    public static MissingServiceRuntimeException newMissingServiceRuntimeException(ServiceIdentifier identifier) {
```
Comment (sleberknight) [inline src/main/java/org/kiwiproject/jersey/client/exception/MissingServiceRuntimeException.java:14]: Suggest renaming to `from`. See the updated comment in #28

File: src/main/java/org/kiwiproject/jersey/client/exception/MissingServiceRuntimeException.java [hunk 2]
```diff
@@ -0,0 +1,23 @@
+package org.kiwiproject.jersey.client.exception;
+
+import static org.kiwiproject.base.KiwiStrings.f;
+
+import org.kiwiproject.jersey.client.ServiceIdentifier;
+
+import java.util.Optional;
+
+public class MissingServiceRuntimeException extends RuntimeException {
```
Comment (sleberknight) [inline src/main/java/org/kiwiproject/jersey/client/exception/MissingServiceRuntimeException.java:9]: Since now public, need some docs on class, constructor, factory.

File: src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java [hunk 3]
```diff
@@ -74,7 +74,7 @@ public WebTarget targetForService(ServiceIdentifier identifier) {
 
         var uri = registryClient.findServiceInstanceBy(instanceQuery)
                 .map(instance -> buildInstanceUri(identifier, instance))
-                .orElseThrow(() -> newMissingServiceRuntimeException(identifier));
+                .orElseThrow(() -> from(identifier));
```
Comment (sleberknight) [inline src/main/java/org/kiwiproject/jersey/client/RegistryAwareClient.java:77]: Generally I don't like to static import small factory methods (e.g. `of`, `from`, etc) since you lose context...

**Review by sleberknight — COMMENTED** [review]
see latest comment...

**Review by sleberknight — APPROVED** [review]
